- name: Install and Configure HTTPD
  hosts: nodes
  become: yes  # Run tasks as sudo
  tasks:
    - name: Install HTTPD
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and Enable HTTPD Service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
